CREATE TABLE "User" ("id" TEXT NOT NULL PRIMARY KEY, "name" TEXT NOT NULL, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "Generation" ("id" TEXT NOT NULL PRIMARY KEY, "userId" TEXT NOT NULL, "modelId" TEXT NOT NULL, "provider" TEXT NOT NULL, "providerGenerationId" TEXT, "prompt" TEXT NOT NULL, "enhancedPrompt" TEXT, "duration" INTEGER NOT NULL, "resolution" TEXT NOT NULL, "aspectRatio" TEXT NOT NULL, "generateAudio" BOOLEAN NOT NULL DEFAULT true, "seed" INTEGER, "status" TEXT NOT NULL, "progress" INTEGER NOT NULL DEFAULT 0, "estimatedCost" REAL, "actualCost" REAL, "creditsReserved" REAL NOT NULL DEFAULT 0, "creditsUsed" REAL NOT NULL DEFAULT 0, "outputPath" TEXT, "thumbnailPath" TEXT, "errorMessage" TEXT, "favorite" BOOLEAN NOT NULL DEFAULT false, "idempotencyKey" TEXT, "parentGenerationId" TEXT, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "startedAt" DATETIME, "completedAt" DATETIME, "canceledAt" DATETIME, CONSTRAINT "Generation_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE RESTRICT ON UPDATE CASCADE, CONSTRAINT "Generation_parentGenerationId_fkey" FOREIGN KEY ("parentGenerationId") REFERENCES "Generation" ("id") ON DELETE SET NULL ON UPDATE CASCADE);
CREATE TABLE "Asset" ("id" TEXT NOT NULL PRIMARY KEY, "type" TEXT NOT NULL, "originalName" TEXT NOT NULL, "storagePath" TEXT NOT NULL, "mimeType" TEXT NOT NULL, "sizeBytes" INTEGER NOT NULL, "width" INTEGER, "height" INTEGER, "duration" REAL, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "GenerationAsset" ("generationId" TEXT NOT NULL, "assetId" TEXT NOT NULL, "role" TEXT NOT NULL, "referenceIndex" INTEGER, PRIMARY KEY ("generationId", "assetId", "role"), CONSTRAINT "GenerationAsset_generationId_fkey" FOREIGN KEY ("generationId") REFERENCES "Generation" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "GenerationAsset_assetId_fkey" FOREIGN KEY ("assetId") REFERENCES "Asset" ("id") ON DELETE RESTRICT ON UPDATE CASCADE);
CREATE TABLE "Model" ("id" TEXT NOT NULL PRIMARY KEY, "displayName" TEXT NOT NULL, "provider" TEXT NOT NULL, "providerModel" TEXT NOT NULL, "enabled" BOOLEAN NOT NULL DEFAULT true, "configurationJson" TEXT NOT NULL);
CREATE TABLE "Setting" ("key" TEXT NOT NULL PRIMARY KEY, "value" TEXT NOT NULL);
CREATE TABLE "CreditWallet" ("id" TEXT NOT NULL PRIMARY KEY, "balance" REAL NOT NULL DEFAULT 1000, "reserved" REAL NOT NULL DEFAULT 0);
CREATE TABLE "CreditTransaction" ("id" TEXT NOT NULL PRIMARY KEY, "type" TEXT NOT NULL, "amount" REAL NOT NULL, "generationId" TEXT, "description" TEXT NOT NULL, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "CreditTransaction_generationId_fkey" FOREIGN KEY ("generationId") REFERENCES "Generation" ("id") ON DELETE SET NULL ON UPDATE CASCADE);
CREATE TABLE "WebhookEvent" ("id" TEXT NOT NULL PRIMARY KEY, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "Preset" ("id" TEXT NOT NULL PRIMARY KEY, "name" TEXT NOT NULL, "description" TEXT NOT NULL, "modelId" TEXT NOT NULL, "aspectRatio" TEXT NOT NULL, "duration" INTEGER NOT NULL, "resolution" TEXT NOT NULL, "promptModifier" TEXT NOT NULL, "generateAudio" BOOLEAN NOT NULL DEFAULT true);
CREATE UNIQUE INDEX "Generation_providerGenerationId_key" ON "Generation"("providerGenerationId");
CREATE UNIQUE INDEX "Generation_idempotencyKey_key" ON "Generation"("idempotencyKey");
CREATE INDEX "Generation_createdAt_idx" ON "Generation"("createdAt");
CREATE INDEX "Generation_status_idx" ON "Generation"("status");
CREATE INDEX "Generation_modelId_idx" ON "Generation"("modelId");
CREATE INDEX "Generation_userId_idx" ON "Generation"("userId");
CREATE UNIQUE INDEX "Asset_storagePath_key" ON "Asset"("storagePath");
CREATE INDEX "Asset_createdAt_idx" ON "Asset"("createdAt");
CREATE INDEX "Asset_type_idx" ON "Asset"("type");
CREATE INDEX "CreditTransaction_generationId_idx" ON "CreditTransaction"("generationId");
